export const GREETINGS = [
  "Merhaba {{name}}, aklında ne var?",
  "Selam {{name}}! Bugün ne keşfediyoruz?",
  "Hoş geldin {{name}}, sana nasıl yardımcı olabilirim?",
  "Harika bir gün {{name}}! Hangi konuyu ele alıyoruz?",
  "Tekrar merhaba {{name}}, ne üzerinde çalışmak istersin?",
  "Günün nasıl geçiyor {{name}}? Başlayalım mı?",
  "İlham dolu bir gün! Ne yaratıyoruz {{name}}?",
  "Seni görmek güzel {{name}}, ne arıyorsun?",
  "Merhaba {{name}}, bugün dünyayı nasıl değiştiriyoruz?",
  "Selam {{name}}, birlikte ne üreteceğiz?",
  "Hoş geldin {{name}}, neye odaklanıyoruz?",
  "Yeni bir fikir mi var {{name}}?",
  "Bugün neyi çözüyoruz {{name}}?",
  "Merhaba {{name}}, sana destek olmaya hazırım.",
  "Selam {{name}}, sıradaki büyük projen ne?",
  "Bugün ne öğreniyoruz {{name}}?",
  "Nasıl gidiyor {{name}}? Aklından geçenler neler?",
  "Seni görmek ne güzel {{name}}! Konumuz nedir?",
  "Hoş geldin {{name}}, bugün seni neler heyecanlandırıyor?",
  "Selam {{name}}, neyi araştırıyoruz?",
  "Yeni bir maceraya hazır mısın {{name}}?",
  "Merhaba {{name}}, hangi soruya cevap arıyorsun?",
  "Ne üzerine düşünüyorsun {{name}}?",
  "Selam {{name}}, bugün sana nasıl ilham verebilirim?",
  "Bugün neyi başarıyoruz {{name}}?",
  "Merhaba {{name}}, aklındaki o parlak fikir ne?",
  "Hoş geldin {{name}}, bugün zihnini ne meşgul ediyor?",
  "Selam {{name}}, üretmeye hazır mıyız?",
  "Merhaba {{name}}, bugün ne tür bir sihre ihtiyacın var?",
  "Günün harika geçsin {{name}}! Ne yapıyoruz?",
  "Seni dinliyorum {{name}}, anlat bakalım.",
  "Selam {{name}}, odaklanmaya hazır mısın?",
  "Hoş geldin {{name}}, neyle başlayalım?",
  "Merhaba {{name}}, bugün listemizde neler var?",
  "Selam {{name}}, bugün hangi sınırları zorluyoruz?",
  "Aklına ne takıldı {{name}}?",
  "Merhaba {{name}}, bugün seni ne motive ediyor?",
  "Hoş geldin {{name}}, yeni bir şeyler denemeye ne dersin?",
  "Selam {{name}}, ne oluşturuyoruz?",
  "Bugün neyi analiz ediyoruz {{name}}?",
  "Merhaba {{name}}, masada hangi konu var?",
  "Selam {{name}}, birlikte düşünelim mi?",
  "Bugün ne tasarlıyoruz {{name}}?",
  "Hoş geldin {{name}}, nereden başlamak istersin?",
  "Merhaba {{name}}, bugün seni şaşırtmama izin ver.",
  "Selam {{name}}, kafanı kurcalayan o düşünce ne?",
  "Hangi problemi çözüyoruz {{name}}?",
  "Merhaba {{name}}, bugün neye ihtiyacın var?",
  "Hoş geldin {{name}}, bugün aklından neler geçiyor?",
  "Selam {{name}}, beyin fırtınası yapalım mı?",
  "Merhaba {{name}}, bugün neyi daha iyi yapıyoruz?",
  "Selam {{name}}, yeni bir şeyler öğrenmeye hazır mısın?",
  "Hoş geldin {{name}}, ne planlıyoruz?",
  "Bugün ne yazıyoruz {{name}}?",
  "Merhaba {{name}}, sana nasıl bir faydam dokunabilir?",
  "Selam {{name}}, günün sorusu nedir?",
  "Bugün hangi fikri canlandırıyoruz {{name}}?",
  "Hoş geldin {{name}}, ne üstünde düşünüyoruz?",
  "Merhaba {{name}}, bugün zihninde ne var?",
  "Selam {{name}}, üretken bir gün olsun! Nereden başlayalım?",
  "Hangi konuya dalıyoruz {{name}}?",
  "Merhaba {{name}}, bugün ne araştırıyoruz?",
  "Selam {{name}}, birlikte ne inşa edeceğiz?",
  "Hoş geldin {{name}}, bugün hangi veriyi inceliyoruz?",
  "Merhaba {{name}}, bugün odak noktamız ne?",
  "Selam {{name}}, yaratıcılığını ne tetikliyor?",
  "Bugün ne tür bir içerik üretiyoruz {{name}}?",
  "Merhaba {{name}}, yeni bir vizyon mu var?",
  "Selam {{name}}, bugün sana nasıl hız kazandırabilirim?",
  "Hoş geldin {{name}}, ne geliştirmek istersin?",
  "Merhaba {{name}}, bugün hangi kelimeler üzerinde oynuyoruz?",
  "Selam {{name}}, bugün zihinsel bir yolculuğa çıkalım mı?",
  "Bugün hangi konuyu tartışıyoruz {{name}}?",
  "Merhaba {{name}}, aklındaki düğümü çözelim mi?",
  "Selam {{name}}, neye çözüm arıyoruz?",
  "Hoş geldin {{name}}, bugün gününü nasıl verimli kılabilirim?",
  "Merhaba {{name}}, bugün ne keşfetmeyi hayal ediyorsun?",
  "Selam {{name}}, neyi baştan tasarlıyoruz?",
  "Bugün ne öğrenmek istersin {{name}}?",
  "Merhaba {{name}}, hangi konuya ışık tutalım?",
  "Selam {{name}}, düşüncelerini benimle paylaş.",
  "Hoş geldin {{name}}, kafanda nasıl bir proje var?",
  "Merhaba {{name}}, bugün neyi mükemmelleştiriyoruz?",
  "Selam {{name}}, yeni bir bakış açısına mı ihtiyacın var?",
  "Bugün hangi kodu yazıyoruz {{name}}?",
  "Merhaba {{name}}, seni dinlemeye her zaman hazırım.",
  "Selam {{name}}, bugünün teması nedir?",
  "Hoş geldin {{name}}, seni ne düşündürüyor?",
  "Merhaba {{name}}, bugün neyi özetliyoruz?",
  "Selam {{name}}, bugün ne başarmak istiyorsun?",
  "Bugün neyi planlıyoruz {{name}}?",
  "Merhaba {{name}}, birlikte ne hayal ediyoruz?",
  "Selam {{name}}, bugün ne kadar uzağa gidiyoruz?",
  "Hoş geldin {{name}}, bugün masaya ne koyuyoruz?",
  "Merhaba {{name}}, aklındakini gerçeğe dönüştürelim mi?",
  "Selam {{name}}, sana nasıl zaman kazandırabilirim?",
  "Bugün ne okuyoruz {{name}}?",
  "Merhaba {{name}}, bugün hangi hikayeyi yazıyoruz?",
  "Selam {{name}}, nasıl bir strateji kuralım?",
  "Hoş geldin {{name}}, günün konusu ne?"
];

export function getRandomGreeting(name: string): string {
  const index = Math.floor(Math.random() * GREETINGS.length);
  const greeting = GREETINGS[index] || "Merhaba {{name}}, aklında ne var?";
  return greeting.replace('{{name}}', name);
}
