"""
Elyan Multi-File Code Generator — LLM-driven code generation with validation

Generates multiple files for a project, validates each with CodeValidator,
and assembles them into a coherent codebase.
"""

import os
from pathlib import Path
from typing import Any, Dict, List, Optional
from utils.logger import get_logger

logger = get_logger("codegen")


# File generation templates (non-LLM fallback)
CODE_TEMPLATES = {
    "fastapi": {
        "main.py": '''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="{title}", version="1.0.0")

app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

@app.get("/")
async def root():
    return {{"message": "Welcome to {title}"}}

@app.get("/health")
async def health():
    return {{"status": "ok"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
''',
        "requirements.txt": "fastapi\\nuvicorn[standard]\\npydantic\\nsqlalchemy\\n",
        "Dockerfile": "FROM python:3.12-slim\\nWORKDIR /app\\nCOPY requirements.txt .\\nRUN pip install --no-cache-dir -r requirements.txt\\nCOPY . .\\nEXPOSE 8000\\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\"]\\n",
    },
    "nextjs": {
        "pages/index.tsx": '''export default function Home() {{
  return (
    <main style={{{{ padding: "2rem" }}}}>
      <h1>{title}</h1>
      <p>Built with Next.js by Elyan</p>
    </main>
  );
}}
''',
        "package.json": '{{"name": "{name}", "version": "1.0.0", "scripts": {{"dev": "next dev", "build": "next build", "start": "next start"}}, "dependencies": {{"next": "latest", "react": "latest", "react-dom": "latest"}}}}',
    },
}


class CodeGenerator:
    """Generates multi-file project code."""

    async def generate_project(
        self,
        architecture: Dict[str, Any],
        output_dir: str,
        llm_client=None,
    ) -> Dict[str, Any]:
        """Generate all files for a project."""
        project_type = architecture.get("project_type", "fastapi")
        files = architecture.get("files", [])
        title = architecture.get("description", "Elyan Project")[:50]
        name = title.lower().replace(" ", "-")[:20]

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        generated = []
        errors = []

        for file_path in files:
            full_path = output_path / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)

            # Check template first
            templates = CODE_TEMPLATES.get(project_type, {})
            if file_path in templates:
                content = templates[file_path].format(title=title, name=name)
            elif llm_client:
                # Generate with LLM
                try:
                    prompt = (
                        f"Generate the content for '{file_path}' in a {project_type} project.\n"
                        f"Project description: {title}\n"
                        f"Other files in project: {', '.join(files)}\n\n"
                        "Return ONLY the file content, no explanations or markdown fences."
                    )
                    content = await llm_client.generate(prompt, role="inference")
                    # Strip markdown fences if present
                    if content.startswith("```"):
                        lines = content.split("\n")
                        content = "\n".join(lines[1:-1]) if lines[-1].strip() == "```" else content
                except Exception as e:
                    content = f"# Auto-generated placeholder for {file_path}\n# Error: {e}\n"
                    errors.append({"file": file_path, "error": str(e)})
            else:
                content = f"# {file_path}\n# Generated by Elyan Delivery Engine\n"

            full_path.write_text(content)
            generated.append(file_path)

        # Validate Python files
        python_files = [f for f in generated if f.endswith(".py")]
        validated = 0
        if python_files:
            try:
                from core.reasoning.code_validator import CodeValidator
                validator = CodeValidator()
                for py_file in python_files:
                    code = (output_path / py_file).read_text()
                    result = await validator.validate_syntax(code)
                    if result.get("valid"):
                        validated += 1
            except Exception:
                pass

        return {
            "success": True,
            "path": str(output_path),
            "files_generated": len(generated),
            "files_validated": validated,
            "errors": errors,
        }


# Global instance
codegen = CodeGenerator()
