from __future__ import annotations

from enum import Enum


class FailureCode(str, Enum):
    INTENT_PARAM_MISSING = "INTENT_PARAM_MISSING"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    SCREEN_SUMMARY_MISSING = "SCREEN_SUMMARY_MISSING"
    BUILD_FAILED = "BUILD_FAILED"
    EMPTY_FILE_OUTPUT = "EMPTY_FILE_OUTPUT"
    DELIVERY_UNSUPPORTED_CHANNEL = "DELIVERY_UNSUPPORTED_CHANNEL"
    UI_TARGET_NOT_FOUND = "UI_TARGET_NOT_FOUND"
    NO_VISUAL_CHANGE = "NO_VISUAL_CHANGE"
    TOOL_CONTRACT_VIOLATION = "TOOL_CONTRACT_VIOLATION"
    MEMORY_PRESSURE = "MEMORY_PRESSURE"
    TIME_BUDGET_EXCEEDED = "TIME_BUDGET_EXCEEDED"
    DOM_UNAVAILABLE = "DOM_UNAVAILABLE"
    NATIVE_DIALOG_REQUIRED = "NATIVE_DIALOG_REQUIRED"
    UNCONTROLLED_BROWSER_CHROME = "UNCONTROLLED_BROWSER_CHROME"
    WRONG_APP_CONTEXT = "WRONG_APP_CONTEXT"
    WRONG_WINDOW_CONTEXT = "WRONG_WINDOW_CONTEXT"
    TEXT_NOT_VERIFIED = "TEXT_NOT_VERIFIED"
    SUBMIT_NOT_VERIFIED = "SUBMIT_NOT_VERIFIED"
    NAVIGATION_NOT_VERIFIED = "NAVIGATION_NOT_VERIFIED"


RETRYABLE_FAILURE_CODES = frozenset(
    {
        FailureCode.INTENT_PARAM_MISSING,
        FailureCode.ARTIFACT_MISSING,
        FailureCode.SCREEN_SUMMARY_MISSING,
        FailureCode.BUILD_FAILED,
        FailureCode.EMPTY_FILE_OUTPUT,
        FailureCode.DELIVERY_UNSUPPORTED_CHANNEL,
        FailureCode.UI_TARGET_NOT_FOUND,
        FailureCode.NO_VISUAL_CHANGE,
        FailureCode.MEMORY_PRESSURE,
        FailureCode.TIME_BUDGET_EXCEEDED,
        FailureCode.DOM_UNAVAILABLE,
        FailureCode.NATIVE_DIALOG_REQUIRED,
        FailureCode.UNCONTROLLED_BROWSER_CHROME,
        FailureCode.WRONG_APP_CONTEXT,
        FailureCode.WRONG_WINDOW_CONTEXT,
        FailureCode.TEXT_NOT_VERIFIED,
        FailureCode.SUBMIT_NOT_VERIFIED,
        FailureCode.NAVIGATION_NOT_VERIFIED,
    }
)


__all__ = ["FailureCode", "RETRYABLE_FAILURE_CODES"]
