import { skillManifestSchema, type SkillManifest } from './types';

const builtinSkillDefinitions: SkillManifest[] = [
  skillManifestSchema.parse({
    id: 'research_companion',
    title: 'Research Companion',
    version: '1.0.0',
    description: 'Plans retrieval-heavy research, citation-first synthesis, and report shaping.',
    domain: 'research',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['research', 'latest', 'current', 'recent', 'compare', 'comparison', 'citation', 'sources', 'report'],
      intents: ['research', 'comparison'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: ['web_crawl', 'web_read_dynamic', 'mcp_bridge'],
    policyBoundary: 'hosted',
    localOnly: false,
    sharedAllowed: true,
    hostedAllowed: true,
    externalActionsAllowed: true,
    auditMode: 'full',
    outputShape: 'report',
    selectionWeight: 35,
    stageTemplates: [
      {
        id: 'research-scan',
        title: 'Research scan',
        summary: 'Resolve intent, surface boundary, and identify the evidence path.',
        kind: 'analysis',
      },
      {
        id: 'research-retrieval',
        title: 'Retrieval',
        summary: 'Expand search and collect the most relevant sources.',
        kind: 'capability',
        capabilityId: 'web_crawl',
      },
      {
        id: 'research-synthesis',
        title: 'Synthesis',
        summary: 'Shape evidence into a structured answer with citations.',
        kind: 'synthesis',
      },
      {
        id: 'research-evaluation',
        title: 'Evaluation',
        summary: 'Check source coverage and citation quality before release.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'workspace_operator',
    title: 'Workspace Operator',
    version: '1.0.0',
    description: 'Handles local files, workspace tasks, and explicit operator flows.',
    domain: 'operator',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['local', 'workspace', 'my files', 'computer', 'device', 'private', 'folder', 'workflow', 'operator'],
      intents: ['personal_workflow', 'procedural'],
      urlSensitive: false,
      documentSensitive: true,
      mcpSensitive: true,
      actionSensitive: true,
    },
    preferredCapabilityIds: ['tool_bridge', 'mcp_bridge', 'browser_automation', 'pdf_extract', 'docx_read'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    outputShape: 'artifact',
    selectionWeight: 32,
    stageTemplates: [
      {
        id: 'operator-boundary',
        title: 'Boundary check',
        summary: 'Keep private context local and avoid unnecessary sync.',
        kind: 'privacy',
      },
      {
        id: 'operator-route',
        title: 'Route selection',
        summary: 'Pick the smallest deterministic capability that solves the task.',
        kind: 'capability',
        capabilityId: 'tool_bridge',
      },
      {
        id: 'operator-execute',
        title: 'Execute',
        summary: 'Run the bounded local action and keep the result auditable.',
        kind: 'capability',
      },
      {
        id: 'operator-evaluate',
        title: 'Evaluation',
        summary: 'Review the action trace and confirm the outcome.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'document_inspector',
    title: 'Document Inspector',
    version: '1.0.0',
    description: 'Extracts structure from PDFs, DOCX files, CSV tables, and other document surfaces.',
    domain: 'documents',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['pdf', 'docx', 'document', 'file', 'csv', 'spreadsheet', 'table', 'extract', 'summarize'],
      intents: ['procedural', 'comparison', 'personal_workflow'],
      urlSensitive: false,
      documentSensitive: true,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: ['pdf_extract', 'docx_read', 'csv_parse', 'csv_export', 'chart_generate'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: false,
    auditMode: 'summary',
    outputShape: 'report',
    selectionWeight: 28,
    stageTemplates: [
      {
        id: 'document-parse',
        title: 'Parse',
        summary: 'Identify the right file surface and parse it deterministically.',
        kind: 'analysis',
        capabilityId: 'pdf_extract',
      },
      {
        id: 'document-transform',
        title: 'Transform',
        summary: 'Normalize extracted content into structured rows or text.',
        kind: 'capability',
      },
      {
        id: 'document-synthesize',
        title: 'Synthesize',
        summary: 'Compress the output into a useful answer or artifact.',
        kind: 'synthesis',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'browser_operator',
    title: 'Browser Operator',
    version: '1.0.0',
    description: 'Reads rendered pages and performs bounded browser actions when explicitly requested.',
    domain: 'browser',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['http', 'https', 'browser', 'click', 'fill', 'inspect', 'render', 'read', 'summarize', 'summarise'],
      intents: ['procedural', 'personal_workflow'],
      urlSensitive: true,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: true,
    },
    preferredCapabilityIds: ['web_read_dynamic', 'browser_automation', 'web_crawl'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    outputShape: 'artifact',
    selectionWeight: 26,
    stageTemplates: [
      {
        id: 'browser-read',
        title: 'Rendered read',
        summary: 'Inspect the live page before taking any action.',
        kind: 'analysis',
        capabilityId: 'web_read_dynamic',
      },
      {
        id: 'browser-action',
        title: 'Bounded action',
        summary: 'Execute only the explicit browser actions requested by the user.',
        kind: 'capability',
        capabilityId: 'browser_automation',
        requiresConfirmation: true,
      },
      {
        id: 'browser-evaluate',
        title: 'Evaluate',
        summary: 'Capture the final page state and verify the result.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'mcp_connector',
    title: 'MCP Connector',
    version: '1.0.0',
    description: 'Routes connected-app requests through explicit MCP surfaces.',
    domain: 'mcp',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['mcp', 'integration', 'prompt', 'resource', 'template', 'tool', 'connect', 'workspace', 'app'],
      intents: ['personal_workflow', 'procedural'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: true,
      actionSensitive: true,
    },
    preferredCapabilityIds: ['mcp_bridge'],
    policyBoundary: 'workspace',
    localOnly: false,
    sharedAllowed: true,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    outputShape: 'artifact',
    selectionWeight: 24,
    stageTemplates: [
      {
        id: 'mcp-discovery',
        title: 'Discovery',
        summary: 'Resolve the live MCP surface before invoking anything.',
        kind: 'mcp',
        capabilityId: 'mcp_bridge',
      },
      {
        id: 'mcp-routing',
        title: 'Route',
        summary: 'Choose the smallest prompt, resource, or tool that fits the task.',
        kind: 'capability',
      },
      {
        id: 'mcp-evaluate',
        title: 'Evaluate',
        summary: 'Keep the trace auditable and make the chosen action obvious.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'deterministic_math',
    title: 'Deterministic Math',
    version: '1.0.0',
    description: 'Uses bounded arithmetic and structured transforms for numeric tasks.',
    domain: 'calculation',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['calculate', 'math', 'sum', 'subtract', 'multiply', 'divide', 'percentage', 'ratio', 'decimal', 'precision'],
      intents: ['direct_answer', 'procedural'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: ['tool_bridge', 'math_exact', 'math_decimal', 'chart_generate'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: false,
    auditMode: 'summary',
    outputShape: 'answer',
    selectionWeight: 22,
    stageTemplates: [
      {
        id: 'math-analysis',
        title: 'Analysis',
        summary: 'Parse the expression and choose the deterministic arithmetic path.',
        kind: 'analysis',
        capabilityId: 'math_exact',
      },
      {
        id: 'math-execution',
        title: 'Execution',
        summary: 'Run the local calculation with bounded precision.',
        kind: 'capability',
        capabilityId: 'tool_bridge',
      },
      {
        id: 'math-evaluate',
        title: 'Evaluate',
        summary: 'Confirm the result is deterministic and stable.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'general_answer',
    title: 'General Answer',
    version: '1.0.0',
    description: 'Fallback skill when no specialized runtime path is a stronger match.',
    domain: 'general',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [],
      intents: ['direct_answer'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: [],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: true,
    hostedAllowed: true,
    externalActionsAllowed: false,
    auditMode: 'summary',
    outputShape: 'answer',
    selectionWeight: 1,
    stageTemplates: [
      {
        id: 'general-analysis',
        title: 'Analysis',
        summary: 'Resolve the request directly with the fewest moving parts.',
        kind: 'analysis',
      },
      {
        id: 'general-synthesis',
        title: 'Synthesis',
        summary: 'Answer clearly without introducing unnecessary surface area.',
        kind: 'synthesis',
      },
      {
        id: 'general-evaluate',
        title: 'Evaluate',
        summary: 'Keep the response concise and easy to trust.',
        kind: 'evaluation',
      },
    ],
  }),
];

export function buildBuiltinSkillCatalog(): SkillManifest[] {
  return builtinSkillDefinitions.map((skill) => skillManifestSchema.parse(skill));
}
