"""Built-in and curated skills/workflow catalog for Elyan."""
from __future__ import annotations

from typing import Dict, Any, List


def get_builtin_skill_catalog() -> Dict[str, Dict[str, Any]]:
    """
    Returns builtin/curated skill metadata keyed by skill name.
    """
    return {
        "system": {
            "name": "system",
            "version": "1.2.0",
            "description": "Sistem kontrolü, ekran görüntüsü, uygulama ve süreç bilgileri",
            "category": "core",
            "integration_type": "desktop",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": ["pyautogui"],
            "required_tools": ["get_system_info", "take_screenshot", "open_app", "close_app", "get_process_info"],
            "python_dependencies": ["pyautogui"],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["sysinfo", "screenshot", "open_app", "close_app", "process"],
            "source": "builtin",
            "latency_level": "real_time",
            "evidence_contract": {
                "requires_artifact": False,
                "requires_verification": True,
                "preferred_signal": "screen_state",
            },
        },
        "files": {
            "name": "files",
            "version": "1.2.0",
            "description": "Dosya okuma/yazma/listeleme/arama operasyonları",
            "category": "productivity",
            "integration_type": "desktop",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": ["list_files", "read_file", "write_file", "search_files", "create_folder"],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["list", "read", "write", "search", "mkdir"],
            "source": "builtin",
            "latency_level": "fast",
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "file_artifact",
            },
        },
        "research": {
            "name": "research",
            "version": "1.3.0",
            "description": "Web araştırma, derin araştırma ve özetleme",
            "category": "analysis",
            "integration_type": "browser",
            "required_scopes": [],
            "auth_strategy": "browser_session",
            "fallback_policy": "web",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": ["httpx", "beautifulsoup4"],
            "required_tools": ["web_search", "fetch_page", "advanced_research"],
            "python_dependencies": ["aiohttp", "beautifulsoup4"],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["search", "deep_research", "summarize"],
            "source": "builtin",
            "latency_level": "slow",
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "source_manifest",
            },
        },
        "lean": {
            "name": "lean",
            "version": "1.0.0",
            "description": "Lean 4 theorem proving, project-scoped formalization and swarm orchestration",
            "category": "formal_methods",
            "integration_type": "code",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": ["lean_status", "lean_project", "lean_workflow", "lean_swarm"],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "curated",
            "hashes": {},
            "commands": ["status", "project", "prove", "draft", "autoprove", "formalize", "autoformalize", "swarm"],
            "source": "builtin",
            "latency_level": "medium",
            "approval_level": 1,
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "lean_build_log",
            },
            "workflow_bundle": {
                "id": "lean_formalization_bundle",
                "required_skills": ["lean", "files", "research"],
                "required_tools": ["lean_status", "lean_project", "lean_workflow", "lean_swarm"],
                "steps": ["lean_status", "lean_project", "lean_workflow", "lean_swarm"],
                "trigger_markers": ["lean", "mathlib", "theorem", "lemma", "prove", "formalize"],
                "executable": False,
                "auto_intent": True,
                "source": "builtin",
            },
        },
        "cloudflare_agents": {
            "name": "cloudflare_agents",
            "version": "1.0.0",
            "description": "Cloudflare Agents starter scaffolding, durable state, realtime sync and workflow bundles",
            "category": "cloud",
            "integration_type": "cloud",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": [
                "cloudflare_agents_status",
                "cloudflare_agents_project",
                "cloudflare_agents_scaffold",
                "cloudflare_agents_workflow",
            ],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "curated",
            "hashes": {},
            "commands": ["status", "project", "scaffold", "workflow"],
            "source": "builtin",
            "latency_level": "medium",
            "approval_level": 1,
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "worker_manifest",
            },
            "workflow_bundle": {
                "id": "cloudflare_agents_starter_bundle",
                "required_skills": ["cloudflare_agents", "code", "research"],
                "required_tools": [
                    "cloudflare_agents_status",
                    "cloudflare_agents_project",
                    "cloudflare_agents_scaffold",
                    "cloudflare_agents_workflow",
                ],
                "steps": [
                    "cloudflare_agents_status",
                    "cloudflare_agents_project",
                    "cloudflare_agents_scaffold",
                    "cloudflare_agents_workflow",
                ],
                "trigger_markers": [
                    "cloudflare agents",
                    "cloudflare worker",
                    "routeAgentRequest",
                    "useAgent",
                    "useAgentChat",
                    "durable objects",
                    "wrangler",
                    "mcp",
                ],
                "executable": False,
                "auto_intent": True,
                "source": "builtin",
            },
        },
        "quivr": {
            "name": "quivr",
            "version": "1.0.0",
            "description": "Quivr second-brain scaffolding, grounded Q&A, workflow tuning and local fallback RAG",
            "category": "knowledge",
            "integration_type": "knowledge",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "local",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": ["quivr_status", "quivr_project", "quivr_scaffold", "quivr_brain_ask"],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "curated",
            "hashes": {},
            "commands": ["status", "project", "scaffold", "ask"],
            "source": "builtin",
            "latency_level": "medium",
            "approval_level": 1,
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "brain_manifest",
            },
            "workflow_bundle": {
                "id": "quivr_second_brain_bootstrap",
                "required_skills": ["quivr", "research", "files"],
                "required_tools": ["quivr_status", "quivr_project", "quivr_scaffold", "quivr_brain_ask"],
                "steps": ["quivr_status", "quivr_scaffold", "quivr_brain_ask"],
                "trigger_markers": [
                    "quivr",
                    "quivr-core",
                    "second brain",
                    "brain.from_files",
                    "retrievalconfig",
                    "retrieval config",
                    "megaparse",
                    "knowledge base",
                    "ask your brain",
                ],
                "executable": False,
                "auto_intent": True,
                "source": "builtin",
            },
        },
        "opengauss": {
            "name": "opengauss",
            "version": "1.0.0",
            "description": "OpenGauss database scaffolding, schema bootstrap, query planning and backup workflows",
            "category": "database",
            "integration_type": "database",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "docker",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": [
                "opengauss_status",
                "opengauss_project",
                "opengauss_scaffold",
                "opengauss_query",
                "opengauss_workflow",
            ],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "curated",
            "hashes": {},
            "commands": ["status", "project", "scaffold", "query", "workflow"],
            "source": "builtin",
            "latency_level": "medium",
            "approval_level": 2,
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "database_manifest",
            },
            "workflow_bundle": {
                "id": "opengauss_database_bootstrap",
                "required_skills": ["opengauss", "files"],
                "required_tools": [
                    "opengauss_status",
                    "opengauss_project",
                    "opengauss_scaffold",
                    "opengauss_query",
                    "opengauss_workflow",
                ],
                "steps": [
                    "opengauss_status",
                    "opengauss_project",
                    "opengauss_scaffold",
                    "opengauss_workflow",
                    "opengauss_query",
                ],
                "trigger_markers": [
                    "opengauss",
                    "gaussdb",
                    "database",
                    "sql",
                    "schema",
                    "migration",
                    "gsql",
                    "backup",
                    "restore",
                ],
                "executable": False,
                "auto_intent": True,
                "source": "builtin",
            },
        },
        "browser": {
            "name": "browser",
            "version": "1.1.0",
            "description": "Tarayıcı otomasyonu ve web navigasyon",
            "category": "automation",
            "integration_type": "browser",
            "required_scopes": [],
            "auth_strategy": "browser_session",
            "fallback_policy": "web",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": ["playwright"],
            "required_tools": ["open_url", "take_screenshot", "extract_text"],
            "python_dependencies": ["playwright", "httpx", "beautifulsoup4"],
            "post_install": ["playwright install chromium"],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["navigate", "screenshot", "extract"],
            "source": "builtin",
            "latency_level": "real_time",
            "evidence_contract": {
                "requires_artifact": False,
                "requires_verification": True,
                "preferred_signal": "screen_state",
            },
        },
        "office": {
            "name": "office",
            "version": "1.1.0",
            "description": "Word/Excel/PDF işleme ve belge üretimi",
            "category": "document",
            "integration_type": "desktop",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": ["python-docx", "openpyxl"],
            "required_tools": ["write_word", "write_excel", "read_pdf", "generate_document_pack"],
            "python_dependencies": ["python-docx", "openpyxl", "pandas", "pypdf", "docxcompose"],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["word", "excel", "pdf", "report_pack"],
            "source": "builtin",
            "latency_level": "medium",
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "document_bundle",
            },
        },
        "email": {
            "name": "email",
            "version": "1.0.0",
            "description": "E-posta gönderme ve inbox işlemleri",
            "category": "communication",
            "integration_type": "email",
            "required_scopes": ["email.read", "email.send"],
            "auth_strategy": "oauth",
            "fallback_policy": "web",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": ["send_email"],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["send", "inbox"],
            "source": "builtin",
            "latency_level": "medium",
            "evidence_contract": {
                "requires_artifact": False,
                "requires_verification": True,
                "preferred_signal": "delivery_receipt",
            },
        },
        "voice": {
            "name": "voice",
            "version": "1.0.0",
            "description": "Konuşma-metin ve metin-konuşma işlemleri",
            "category": "multimodal",
            "integration_type": "desktop",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": ["openai-whisper", "pyttsx3"],
            "required_tools": ["transcribe_audio_file", "speak_text_local"],
            "python_dependencies": ["openai-whisper", "pyttsx3", "sounddevice"],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["transcribe", "speak"],
            "source": "curated",
            "latency_level": "real_time",
            "evidence_contract": {
                "requires_artifact": False,
                "requires_verification": True,
                "preferred_signal": "audio_state",
            },
        },
        "calendar": {
            "name": "calendar",
            "version": "1.0.0",
            "description": "Takvim ve hatırlatıcı yönetimi",
            "category": "productivity",
            "integration_type": "scheduler",
            "required_scopes": ["calendar.read", "calendar.write"],
            "auth_strategy": "oauth",
            "fallback_policy": "web",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": [],
            "required_tools": ["get_today_events", "create_event", "create_reminder"],
            "python_dependencies": [],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["today", "create_event", "reminder"],
            "source": "curated",
            "latency_level": "medium",
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "calendar_entry",
            },
        },
        "multimodal": {
            "name": "multimodal",
            "version": "1.0.0",
            "description": "Görsel paket üretimi ve görsel analiz",
            "category": "multimodal",
            "integration_type": "desktop",
            "required_scopes": [],
            "auth_strategy": "none",
            "fallback_policy": "native",
            "supported_platforms": ["windows", "darwin", "linux"],
            "dependencies": ["Pillow", "mss", "numpy", "opencv-python", "pyautogui"],
            "required_tools": ["create_visual_asset_pack", "analyze_and_narrate_image"],
            "python_dependencies": ["Pillow", "mss", "numpy", "opencv-python", "pyautogui"],
            "post_install": [],
            "trust_level": "trusted",
            "hashes": {},
            "commands": ["visual_pack", "analyze_image"],
            "source": "curated",
            "latency_level": "medium",
            "evidence_contract": {
                "requires_artifact": True,
                "requires_verification": True,
                "preferred_signal": "visual_bundle",
            },
        },
    }


def get_builtin_workflow_catalog() -> Dict[str, Dict[str, Any]]:
    """
    Skill+tool linked workflow templates.
    - executable=True: deterministik olarak doğrudan çalıştırılabilir
    - executable=False: entegrasyon şablonu (plan/recipe)
    """
    return {
        "lean_project_bootstrap": {
            "id": "lean_project_bootstrap",
            "name": "Lean Project Bootstrap",
            "version": "1.0.0",
            "description": "Register or create a Lean project and prepare workflow state.",
            "category": "formal_methods",
            "required_skills": ["lean", "files"],
            "required_tools": ["lean_project", "lean_status", "write_file"],
            "steps": ["lean_project", "lean_status"],
            "trigger_markers": ["lean project", "project init", "lakefile.lean", "lean-toolchain"],
            "executable": False,
            "auto_intent": True,
            "source": "builtin",
        },
        "lean_formalization_loop": {
            "id": "lean_formalization_loop",
            "name": "Lean Formalization Loop",
            "version": "1.0.0",
            "description": "Drive prove/draft/autoprove/formalize loops for Lean projects.",
            "category": "formal_methods",
            "required_skills": ["lean", "files", "research"],
            "required_tools": ["lean_status", "lean_workflow", "run_safe_command"],
            "steps": ["lean_status", "lean_workflow"],
            "trigger_markers": ["prove", "draft", "formalize", "autoprove", "autoformalize", "theorem", "lemma", "mathlib"],
            "executable": False,
            "auto_intent": True,
            "source": "builtin",
        },
        "quivr_second_brain_bootstrap": {
            "id": "quivr_second_brain_bootstrap",
            "name": "Quivr Second Brain Bootstrap",
            "version": "1.0.0",
            "description": "Scaffold a Quivr second brain and wire the retrieval loop for local Q&A.",
            "category": "knowledge",
            "required_skills": ["quivr", "research", "files"],
            "required_tools": ["quivr_status", "quivr_scaffold", "quivr_brain_ask"],
            "steps": ["quivr_status", "quivr_scaffold", "quivr_brain_ask"],
            "trigger_markers": ["quivr", "quivr-core", "second brain", "brain.from_files", "retrievalconfig"],
            "executable": False,
            "auto_intent": True,
            "source": "builtin",
        },
        "opengauss_database_bootstrap": {
            "id": "opengauss_database_bootstrap",
            "name": "OpenGauss Database Bootstrap",
            "version": "1.0.0",
            "description": "Scaffold an OpenGauss workspace and prepare a reproducible database query loop.",
            "category": "database",
            "required_skills": ["opengauss", "files"],
            "required_tools": ["opengauss_status", "opengauss_scaffold", "opengauss_query"],
            "steps": ["opengauss_status", "opengauss_scaffold", "opengauss_workflow", "opengauss_query"],
            "trigger_markers": ["opengauss", "gaussdb", "database", "sql", "schema", "migration", "backup", "restore"],
            "executable": False,
            "auto_intent": True,
            "source": "builtin",
        },
        "opengauss_query_loop": {
            "id": "opengauss_query_loop",
            "name": "OpenGauss Query Loop",
            "version": "1.0.0",
            "description": "Prepare and review OpenGauss read-only SQL commands against a project workspace.",
            "category": "database",
            "required_skills": ["opengauss", "research"],
            "required_tools": ["opengauss_status", "opengauss_query"],
            "steps": ["opengauss_status", "opengauss_query"],
            "trigger_markers": ["select", "explain", "sql", "gsql", "opengauss", "gaussdb"],
            "executable": False,
            "auto_intent": True,
            "source": "builtin",
        },
        "wallpaper_with_proof": {
            "id": "wallpaper_with_proof",
            "name": "Wallpaper + Proof",
            "version": "1.0.0",
            "description": "Görselden duvar kağıdı ayarla ve kanıt ekran görüntüsü üret.",
            "category": "desktop",
            "required_skills": ["system", "files"],
            "required_tools": ["set_wallpaper", "take_screenshot"],
            "steps": ["set_wallpaper", "take_screenshot"],
            "trigger_markers": ["duvar kağıdı", "wallpaper", "arka plan"],
            "executable": True,
            "auto_intent": True,
            "source": "builtin",
        },
        "api_health_get_save": {
            "id": "api_health_get_save",
            "name": "API Health + GET + Save",
            "version": "1.0.0",
            "description": "Endpoint health check + GET isteği + result.json/summary.txt kaydı.",
            "category": "integration",
            "required_skills": ["research", "files"],
            "required_tools": ["api_health_check", "http_request", "write_file"],
            "steps": ["api_health_check", "http_request", "write_file", "write_file"],
            "trigger_markers": ["health check", "get", "result.json", "summary.txt"],
            "executable": True,
            "auto_intent": True,
            "source": "builtin",
        },
        "office_sales_report_pipeline": {
            "id": "office_sales_report_pipeline",
            "name": "Sales Report Pipeline",
            "version": "1.0.0",
            "description": "ERP/CRM satış verisi -> analiz -> rapor/PDF -> mail akışı için şablon.",
            "category": "office",
            "required_skills": ["office", "email", "research"],
            "required_tools": ["read_excel", "analyze_excel_data", "write_word", "generate_document_pack", "send_email"],
            "steps": ["read_excel", "analyze_excel_data", "write_word", "generate_document_pack", "send_email"],
            "trigger_markers": ["satış raporu", "pdf", "yönetime mail"],
            "executable": False,
            "auto_intent": False,
            "source": "builtin",
        },
        "contract_expiry_scan": {
            "id": "contract_expiry_scan",
            "name": "Contract Expiry Scan",
            "version": "1.0.0",
            "description": "Sözleşme klasörlerini tarayıp bitiş tarihi yaklaşanları raporlar.",
            "category": "compliance",
            "required_skills": ["files", "office"],
            "required_tools": ["search_files", "read_file", "write_file"],
            "steps": ["search_files", "read_file", "write_file"],
            "trigger_markers": ["sözleşme", "süresi dolacak", "contract expiry"],
            "executable": False,
            "auto_intent": False,
            "source": "builtin",
        },
        "incident_log_analysis": {
            "id": "incident_log_analysis",
            "name": "Incident Log Analysis",
            "version": "1.0.0",
            "description": "Log dosyalarını analiz edip hata özeti ve aksiyon listesi üretir.",
            "category": "ops",
            "required_skills": ["system", "files", "research"],
            "required_tools": ["search_files", "read_file", "write_file", "run_safe_command"],
            "steps": ["search_files", "read_file", "run_safe_command", "write_file"],
            "trigger_markers": ["log analiz", "incident", "hata raporu"],
            "executable": False,
            "auto_intent": False,
            "source": "builtin",
        },
        "priority_planning_assistant": {
            "id": "priority_planning_assistant",
            "name": "Priority Planning",
            "version": "1.0.0",
            "description": "Görevleri önceliklendirip zaman planı şablonu çıkarır.",
            "category": "planning",
            "required_skills": ["research", "calendar"],
            "required_tools": ["create_reminder", "create_event", "write_file"],
            "steps": ["create_event", "create_reminder", "write_file"],
            "trigger_markers": ["önceliklendir", "acil 3 iş", "takvime yerleştir"],
            "executable": False,
            "auto_intent": False,
            "source": "builtin",
        },
    }


def list_catalog() -> List[Dict[str, Any]]:
    return list(get_builtin_skill_catalog().values())


def list_workflow_catalog() -> List[Dict[str, Any]]:
    return list(get_builtin_workflow_catalog().values())
