import { skillManifestSchema, type SkillManifest } from './types';

const agenticTechniques = {
  scqaWritingFramework: {
    id: 'scqa-writing-framework',
    title: 'SCQA Writing Framework',
    category: 'writing_content' as const,
    description: 'Structures content with Situation, Complication, Question, and Answer.',
    keywords: ['scqa', 'situation', 'complication', 'question', 'answer', 'structured writing', 'narrative'],
    instruction: 'Use Situation, Complication, Question, and Answer sections. Keep each section concise and logically connected.',
    outputHint: 'SCQA sections with short paragraphs and no repeated setup.',
  },
  contentRepurposingEngine: {
    id: 'content-repurposing-engine',
    title: 'Content Repurposing Engine',
    category: 'writing_content' as const,
    description: 'Converts source material into channel-specific formats while preserving meaning.',
    keywords: ['repurpose', 'thread', 'social', 'short-form', 'long-form', 'platform', 'content formats'],
    instruction: 'Extract the core message, adapt it to the requested channel, and preserve tone and meaning.',
    outputHint: 'Platform-specific copy with clear hooks, sections, and compact formatting.',
  },
  toneStyleEnforcer: {
    id: 'tone-style-enforcer',
    title: 'Tone & Style Enforcer',
    category: 'writing_content' as const,
    description: 'Keeps output aligned with a declared brand, personal, or product voice.',
    keywords: ['tone', 'style', 'voice', 'brand voice', 'consistent', 'rewrite in style'],
    instruction: 'Apply the requested tone consistently, remove style drift, and keep the result clear.',
    outputHint: 'Clean text aligned to the requested style guide.',
  },
  longFormSummaryCompressor: {
    id: 'long-form-summary-compressor',
    title: 'Long-Form Summary Compressor',
    category: 'writing_content' as const,
    description: 'Compresses long content into a concise summary without losing critical points.',
    keywords: ['summarize', 'summary', 'compress', 'condense', 'long-form', 'key points'],
    instruction: 'Identify the essential points, remove redundancy, and keep important caveats.',
    outputHint: 'Concise summary with optional bullets for the highest-value points.',
  },
  structuredCopywritingSkill: {
    id: 'structured-copywriting-skill',
    title: 'Structured Copywriting Skill',
    category: 'writing_content' as const,
    description: 'Creates persuasive copy with a clear hook, flow, and call to action.',
    keywords: ['copywriting', 'copy', 'hook', 'cta', 'marketing', 'landing copy', 'sales copy'],
    instruction: 'Start with a strong hook, organize benefits clearly, and include an actionable close when appropriate.',
    outputHint: 'Structured copy with hook, body, and concise CTA.',
  },
  excalidrawDiagramGenerator: {
    id: 'excalidraw-diagram-generator',
    title: 'Excalidraw Diagram Generator',
    category: 'visual_infographic' as const,
    description: 'Turns a concept or workflow into diagram-ready nodes and connections.',
    keywords: ['excalidraw', 'diagram', 'nodes', 'connectors', 'map', 'visualize workflow'],
    instruction: 'Identify the main elements, define nodes, connect them logically, and suggest a simple layout.',
    outputHint: 'Diagram title, nodes, connections, and layout guidance.',
  },
  infographicBuilder: {
    id: 'infographic-builder',
    title: 'Infographic Builder',
    category: 'visual_infographic' as const,
    description: 'Organizes content into visual-friendly infographic sections.',
    keywords: ['infographic', 'visual summary', 'visual report', 'steps', 'educational visual'],
    instruction: 'Extract the key points and arrange them into concise visual sections with clear hierarchy.',
    outputHint: 'Infographic-ready headings, steps, and short text blocks.',
  },
  flowchartDecisionBuilder: {
    id: 'flowchart-decision-builder',
    title: 'Flowchart Decision Builder',
    category: 'visual_infographic' as const,
    description: 'Creates decision-tree or flowchart structures from process text.',
    keywords: ['flowchart', 'decision tree', 'decision', 'branch', 'if then', 'process map'],
    instruction: 'Map steps and decisions into a minimal flow with explicit branch labels.',
    outputHint: 'Flowchart nodes, decision branches, and terminal outcomes.',
  },
  uiUxLayoutAdvisor: {
    id: 'ui-ux-layout-advisor',
    title: 'UI/UX Layout Advisor',
    category: 'visual_infographic' as const,
    description: 'Advises on spacing, hierarchy, usability, and interface layout.',
    keywords: ['ui', 'ux', 'layout', 'spacing', 'hierarchy', 'accessibility', 'interface'],
    instruction: 'Prioritize hierarchy, spacing, alignment, accessibility, and workflow clarity.',
    outputHint: 'Layout guidance with concrete positioning and interaction notes.',
  },
  deepResearchSynthesizer: {
    id: 'deep-research-synthesizer',
    title: 'Deep Research Synthesizer',
    category: 'research_analysis' as const,
    description: 'Filters large research input into patterns, insights, and takeaways.',
    keywords: ['deep research', 'synthesize', 'synthesis', 'patterns', 'insights', 'large dataset'],
    instruction: 'Filter low-value material, identify patterns, and separate insight from supporting detail.',
    outputHint: 'Key insights, supporting details, and a concise synthesis.',
  },
  onchainTransactionAnalyzer: {
    id: 'onchain-transaction-analyzer',
    title: 'Onchain Transaction Analyzer',
    category: 'research_analysis' as const,
    description: 'Explains wallets, contracts, and token movements in plain language.',
    keywords: ['onchain', 'blockchain', 'wallet', 'transaction', 'token flow', 'contract', 'crypto'],
    instruction: 'Trace actors, token movement, contracts, and likely intent in plain language without overclaiming.',
    outputHint: 'Step-by-step transaction explanation with actors and summary insight.',
  },
  sourceValidationSkill: {
    id: 'source-validation-skill',
    title: 'Source Validation Skill',
    category: 'research_analysis' as const,
    description: 'Evaluates source reliability, relevance, date, and potential bias.',
    keywords: ['source validation', 'validate sources', 'credibility', 'bias', 'reliability', 'references'],
    instruction: 'Evaluate source authority, recency, relevance, and bias before drawing conclusions.',
    outputHint: 'Verified source notes, reliability concerns, and grounded conclusions.',
  },
  competitiveIntelligenceSkill: {
    id: 'competitive-intelligence-skill',
    title: 'Competitive Intelligence Skill',
    category: 'research_analysis' as const,
    description: 'Compares products, protocols, or tools across strengths, weaknesses, and opportunities.',
    keywords: ['competitive', 'competitor', 'compare products', 'swot', 'market analysis', 'alternatives'],
    instruction: 'Compare competitors on relevant dimensions and turn differences into actionable takeaways.',
    outputHint: 'Comparison bullets, strengths, weaknesses, risks, and recommendations.',
  },
  optimizationModelingPlaybook: {
    id: 'optimization-modeling-playbook',
    title: 'Optimization Modeling Playbook',
    category: 'research_analysis' as const,
    description: 'Maps assignment, routing, scheduling, and resource allocation problems into explicit binary models.',
    keywords: [
      'model problem',
      'qubo',
      'ising',
      'variables',
      'constraints',
      'objective',
      'assignment',
      'resource allocation',
      'best distribution',
      'en iyi dağıtım',
      'load balancing',
    ],
    instruction: 'State the objective, decision variables, constraints, and penalty terms before solving. Keep the problem formulation explicit.',
    outputHint: 'Problem model with objective, variables, constraints, and penalty framing.',
  },
  optimizationSolverComparator: {
    id: 'optimization-solver-comparator',
    title: 'Optimization Solver Comparator',
    category: 'research_analysis' as const,
    description: 'Compares classical and quantum-inspired solver outputs with feasibility and cost clarity.',
    keywords: ['solver comparison', 'greedy', 'simulated annealing', 'bruteforce', 'feasible', 'cost', 'energy', 'solver'],
    instruction: 'Compare solvers on feasibility, total cost, violation count, runtime, and explanation quality. Favor the most transparent result.',
    outputHint: 'Solver comparison with costs, violations, runtime, and recommendation.',
  },
  optimizationDecisionReporter: {
    id: 'optimization-decision-reporter',
    title: 'Optimization Decision Reporter',
    category: 'writing_content' as const,
    description: 'Turns an optimization run into a clear decision report with technical honesty.',
    keywords: [
      'decision report',
      'recommended solution',
      'selected solution',
      'solver results',
      'feasibility',
      'summary',
      'explain solution',
      'report',
      'recommendation',
    ],
    instruction: 'Summarize the selected solution, explain why it was chosen, and state any uncertainty or unsupported assumptions plainly.',
    outputHint: 'Concise decision report with recommendation and caveats.',
  },
  knowledgeStructuringSkill: {
    id: 'knowledge-structuring-skill',
    title: 'Knowledge Structuring Skill',
    category: 'writing_content' as const,
    description: 'Turns messy information into a clear framework or structured notes.',
    keywords: ['structure knowledge', 'organize', 'framework', 'notes', 'outline', 'categorize'],
    instruction: 'Group related ideas, name the major categories, and remove ambiguity.',
    outputHint: 'Structured framework with clear categories and compact notes.',
  },
  videoScriptGenerator: {
    id: 'video-script-generator',
    title: 'Video Script Generator',
    category: 'video_content' as const,
    description: 'Creates video scripts with hook, pacing, sections, and closing.',
    keywords: ['video script', 'script', 'short video', 'youtube', 'reel', 'tiktok', 'pacing'],
    instruction: 'Open with a hook, structure the content into paced sections, and close with a clear action or takeaway.',
    outputHint: 'Hook, timed or sectioned script beats, and closing line.',
  },
  videoEditingPlanner: {
    id: 'video-editing-planner',
    title: 'Video Editing Planner',
    category: 'video_content' as const,
    description: 'Plans cuts, transitions, scene structure, and pacing for video edits.',
    keywords: ['video editing', 'editing plan', 'cuts', 'transitions', 'scene', 'b-roll', 'pacing'],
    instruction: 'Break the story into scenes, suggest cuts and transitions, and keep edits in service of clarity.',
    outputHint: 'Scene-by-scene edit plan with pacing and transition notes.',
  },
  hookGenerator: {
    id: 'hook-generator',
    title: 'Hook Generator',
    category: 'video_content' as const,
    description: 'Generates concise hooks for intros, posts, and videos.',
    keywords: ['hook', 'opening line', 'intro', 'attention', 'headline', 'viral'],
    instruction: 'Create concise, relevant hooks built on curiosity, contrast, or a concrete promise.',
    outputHint: 'Multiple short hook options with optional follow-up line.',
  },
  captionSubtitleFormatter: {
    id: 'caption-subtitle-formatter',
    title: 'Caption & Subtitle Formatter',
    category: 'video_content' as const,
    description: 'Formats captions and subtitles for readability and timing.',
    keywords: ['caption', 'subtitle', 'srt', 'timing', 'accessibility', 'line breaks'],
    instruction: 'Keep lines short, readable, and aligned to speech timing or natural phrase breaks.',
    outputHint: 'Caption blocks or timed subtitle cues with concise lines.',
  },
  codeReviewSkill: {
    id: 'code-review-skill',
    title: 'Code Review Skill',
    category: 'coding_automation' as const,
    description: 'Reviews code for bugs, regressions, maintainability, and missing tests.',
    keywords: ['code review', 'review code', 'bug', 'regression', 'maintainability', 'best practices'],
    instruction: 'Prioritize concrete bugs, regressions, risks, and missing tests with actionable fixes.',
    outputHint: 'Findings first, ordered by severity, with file or behavior references.',
  },
  workflowAutomationAgent: {
    id: 'workflow-automation-agent',
    title: 'Workflow Automation Agent',
    category: 'coding_automation' as const,
    description: 'Breaks complex goals into stepwise workflows with tool mapping.',
    keywords: ['workflow', 'automation', 'automate', 'step-by-step', 'process', 'tool mapping'],
    instruction: 'Decompose the goal into executable steps, assign tools, and remove vague handoffs.',
    outputHint: 'Goal, ordered workflow, tool mapping, and verification steps.',
  },
  skillCreatorMetaSkill: {
    id: 'skill-creator-meta-skill',
    title: 'Skill Creator Meta Skill',
    category: 'coding_automation' as const,
    description: 'Creates structured skill definitions in markdown-style format.',
    keywords: ['create skill', 'skill creator', 'meta skill', 'skill.md', 'agentic skill'],
    instruction: 'Define the skill purpose, triggers, process, constraints, and output contract clearly.',
    outputHint: 'Ready-to-use skill definition with metadata and instructions.',
  },
  devopsAssistant: {
    id: 'devops-assistant',
    title: 'DevOps Assistant',
    category: 'coding_automation' as const,
    description: 'Supports deployment, versioning, release, and workflow operations.',
    keywords: ['devops', 'deploy', 'deployment', 'release', 'ci', 'cd', 'workflow', 'version'],
    instruction: 'Map the operational workflow, identify verification gates, and keep release steps explicit.',
    outputHint: 'Stepwise DevOps plan with checks, rollback notes, and automation suggestions.',
  },
};

const builtinSkillDefinitions: SkillManifest[] = [
  skillManifestSchema.parse({
    id: 'research_companion',
    title: 'Research Companion',
    version: '1.0.0',
    description: 'Plans retrieval-heavy research, citation-first synthesis, and report shaping.',
    domain: 'research',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['research', 'latest', 'current', 'recent', 'compare', 'comparison', 'citation', 'sources', 'report'],
      intents: ['research', 'comparison'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: ['web_crawl', 'web_read_dynamic', 'mcp_bridge'],
    policyBoundary: 'hosted',
    localOnly: false,
    sharedAllowed: true,
    hostedAllowed: true,
    externalActionsAllowed: true,
    auditMode: 'full',
    riskLevel: 'read_only',
    approvalLevel: 'AUTO',
    inputContract: {
      summary: 'Research query, freshness requirement, and source constraints.',
    },
    outputContract: {
      summary: 'Citation-aware report with explicit source coverage and uncertainty.',
    },
    verificationMode: 'trace',
    outputShape: 'report',
    selectionWeight: 35,
    stageTemplates: [
      {
        id: 'research-scan',
        title: 'Research scan',
        summary: 'Resolve intent, surface boundary, and identify the evidence path.',
        kind: 'analysis',
      },
      {
        id: 'research-retrieval',
        title: 'Retrieval',
        summary: 'Expand search and collect the most relevant sources.',
        kind: 'capability',
        capabilityId: 'web_crawl',
      },
      {
        id: 'research-synthesis',
        title: 'Synthesis',
        summary: 'Shape evidence into a structured answer with citations.',
        kind: 'synthesis',
      },
      {
        id: 'research-evaluation',
        title: 'Evaluation',
        summary: 'Check source coverage and citation quality before release.',
        kind: 'evaluation',
      },
    ],
    techniques: [
      agenticTechniques.deepResearchSynthesizer,
      agenticTechniques.sourceValidationSkill,
      agenticTechniques.competitiveIntelligenceSkill,
      agenticTechniques.onchainTransactionAnalyzer,
    ],
  }),
  skillManifestSchema.parse({
    id: 'workspace_operator',
    title: 'Workspace Operator',
    version: '1.0.0',
    description: 'Handles local files, code tasks, workspace work, and explicit operator flows.',
    domain: 'operator',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [
        'local',
        'workspace',
        'my files',
        'computer',
        'device',
        'private',
        'folder',
        'workflow',
        'operator',
        'code',
        'repo',
        'repository',
        'branch',
        'commit',
        'diff',
        'patch',
        'refactor',
        'review',
        'debug',
        'test',
        'build',
        'lint',
        'deploy',
        'design',
        'layout',
        'wireframe',
        'mockup',
        'figma',
        'ui',
        'ux',
      ],
      intents: ['personal_workflow', 'procedural'],
      urlSensitive: false,
      documentSensitive: true,
      mcpSensitive: true,
      actionSensitive: true,
    },
    preferredCapabilityIds: [
      'tool_bridge',
      'mcp_bridge',
      'browser_automation',
      'pdf_extract',
      'docx_read',
      'docx_write',
      'markdown_render',
    ],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    riskLevel: 'write_sensitive',
    approvalLevel: 'SCREEN',
    inputContract: {
      summary: 'Bounded local task intent plus allowed workspace roots and requested action.',
    },
    outputContract: {
      summary: 'Auditable artifact, diff, trace, or operator result with verification notes.',
    },
    verificationMode: 'artifact',
    outputShape: 'artifact',
    selectionWeight: 32,
    stageTemplates: [
      {
        id: 'operator-boundary',
        title: 'Boundary check',
        summary: 'Keep private context local and avoid unnecessary sync.',
        kind: 'privacy',
      },
      {
        id: 'operator-route',
        title: 'Route selection',
        summary: 'Pick the smallest deterministic capability that solves the task.',
        kind: 'capability',
        capabilityId: 'tool_bridge',
      },
      {
        id: 'operator-execute',
        title: 'Execute',
        summary: 'Run the smallest bounded local action and keep the result auditable.',
        kind: 'capability',
      },
      {
        id: 'operator-evaluate',
        title: 'Evaluation',
        summary: 'Review the trace, diff, or artifact before release.',
        kind: 'evaluation',
      },
    ],
    techniques: [
      agenticTechniques.codeReviewSkill,
      agenticTechniques.workflowAutomationAgent,
      agenticTechniques.devopsAssistant,
      agenticTechniques.skillCreatorMetaSkill,
    ],
  }),
  skillManifestSchema.parse({
    id: 'document_inspector',
    title: 'Document Inspector',
    version: '1.0.0',
    description: 'Extracts structure from PDFs, DOCX files, CSV tables, and document drafts.',
    domain: 'documents',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [
        'pdf',
        'docx',
        'document',
        'file',
        'doc',
        'csv',
        'spreadsheet',
        'table',
        'extract',
        'summarize',
        'summarise',
        'xlsx',
        'xls',
        'ods',
        'zip',
        'archive',
        'ocr',
        'scan',
        'yaml',
        'xml',
        'frontmatter',
        'markdown',
        'brief',
        'spec',
        'proposal',
        'rfc',
        'prd',
        'readme',
        'outline',
        'docs',
      ],
      intents: ['procedural', 'comparison', 'personal_workflow'],
      urlSensitive: false,
      documentSensitive: true,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: [
      'pdf_extract',
      'pdf_workflow',
      'docx_read',
      'csv_parse',
      'csv_export',
      'spreadsheet_read',
      'spreadsheet_write',
      'archive_zip',
      'ocr_image',
      'metadata_parse',
      'markdown_render',
      'local_search_index',
      'chart_generate',
      'docx_write',
    ],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: false,
    auditMode: 'summary',
    riskLevel: 'write_safe',
    approvalLevel: 'CONFIRM',
    inputContract: {
      summary: 'Document path or content plus the requested extraction, transform, or export.',
    },
    outputContract: {
      summary: 'Structured document summary, transformed rows, or generated document artifact.',
    },
    verificationMode: 'artifact',
    outputShape: 'report',
    selectionWeight: 28,
    stageTemplates: [
      {
        id: 'document-parse',
        title: 'Parse',
        summary: 'Identify the right file surface and parse it deterministically.',
        kind: 'analysis',
        capabilityId: 'pdf_extract',
      },
      {
        id: 'document-transform',
        title: 'Transform',
        summary: 'Normalize extracted content into structured rows, notes, or draft text.',
        kind: 'capability',
      },
      {
        id: 'document-synthesize',
        title: 'Synthesize',
        summary: 'Compress the output into a useful answer, brief, or artifact.',
        kind: 'synthesis',
      },
    ],
    techniques: [
      agenticTechniques.scqaWritingFramework,
      agenticTechniques.longFormSummaryCompressor,
      agenticTechniques.knowledgeStructuringSkill,
      agenticTechniques.contentRepurposingEngine,
      agenticTechniques.captionSubtitleFormatter,
    ],
  }),
  skillManifestSchema.parse({
    id: 'design_producer',
    title: 'Design Producer',
    version: '1.0.0',
    description: 'Turns product, UI, prototype, and visual direction requests into inspectable design artifacts without generic AI patterns.',
    domain: 'design',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [
        'design',
        'ui',
        'ux',
        'prototype',
        'mockup',
        'layout',
        'redesign',
        'visual',
        'brand',
        'story',
        'slide',
        'presentation',
        'animation',
        'landing',
        'website',
        'app screen',
        'interface',
        'premium',
      ],
      intents: ['procedural', 'personal_workflow'],
      urlSensitive: true,
      documentSensitive: true,
      mcpSensitive: false,
      actionSensitive: true,
    },
    preferredCapabilityIds: [
      'web_read_dynamic',
      'browser_automation',
      'markdown_render',
      'docx_write',
      'chart_generate',
      'image_metadata',
    ],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    riskLevel: 'write_safe',
    approvalLevel: 'CONFIRM',
    inputContract: {
      summary: 'Product intent, target audience, existing UI/assets when available, and desired output format.',
    },
    outputContract: {
      summary: 'Design brief, prototype plan, UI artifact, or implementation-ready visual direction with verification notes.',
    },
    verificationMode: 'artifact',
    outputShape: 'artifact',
    selectionWeight: 31,
    stageTemplates: [
      {
        id: 'design-context',
        title: 'Context audit',
        summary: 'Inspect existing product context, assets, UI constraints, and audience before proposing visuals.',
        kind: 'analysis',
      },
      {
        id: 'design-direction',
        title: 'Direction',
        summary: 'Select a visual direction with explicit density, motion, and variance settings.',
        kind: 'synthesis',
      },
      {
        id: 'design-artifact',
        title: 'Artifact',
        summary: 'Produce the smallest useful design artifact: brief, prototype plan, page, deck, or implementation notes.',
        kind: 'capability',
        requiresConfirmation: true,
      },
      {
        id: 'design-review',
        title: 'Review',
        summary: 'Check hierarchy, spacing, responsiveness, loading/empty/error states, and anti-generic design quality.',
        kind: 'evaluation',
      },
    ],
    techniques: [
      agenticTechniques.infographicBuilder,
      agenticTechniques.excalidrawDiagramGenerator,
      agenticTechniques.flowchartDecisionBuilder,
      agenticTechniques.uiUxLayoutAdvisor,
    ],
  }),
  skillManifestSchema.parse({
    id: 'browser_operator',
    title: 'Browser Operator',
    version: '1.0.0',
    description: 'Reads rendered pages and performs bounded browser actions when explicitly requested.',
    domain: 'browser',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['http', 'https', 'browser', 'click', 'fill', 'inspect', 'render', 'read', 'summarize', 'summarise'],
      intents: ['procedural', 'personal_workflow'],
      urlSensitive: true,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: true,
    },
    preferredCapabilityIds: ['web_read_dynamic', 'browser_automation', 'web_crawl'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    riskLevel: 'write_safe',
    approvalLevel: 'CONFIRM',
    inputContract: {
      summary: 'Rendered page URL, explicit user action, and bounded browser scope.',
    },
    outputContract: {
      summary: 'Browser result with visible final state and action trace.',
    },
    verificationMode: 'trace',
    outputShape: 'artifact',
    selectionWeight: 26,
    stageTemplates: [
      {
        id: 'browser-read',
        title: 'Rendered read',
        summary: 'Inspect the live page before taking any action.',
        kind: 'analysis',
        capabilityId: 'web_read_dynamic',
      },
      {
        id: 'browser-action',
        title: 'Bounded action',
        summary: 'Execute only the explicit browser actions requested by the user.',
        kind: 'capability',
        capabilityId: 'browser_automation',
        requiresConfirmation: true,
      },
      {
        id: 'browser-evaluate',
        title: 'Evaluate',
        summary: 'Capture the final page state and verify the result.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'mcp_connector',
    title: 'MCP Connector',
    version: '1.0.0',
    description: 'Routes connected-app requests through explicit MCP surfaces.',
    domain: 'mcp',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [
        'mcp',
        'integration',
        'prompt',
        'resource',
        'template',
        'tool',
        'connect',
        'workspace',
        'app',
        'gmail',
        'calendar',
        'notion',
        'github',
      ],
      intents: ['personal_workflow', 'procedural'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: true,
      actionSensitive: true,
    },
    preferredCapabilityIds: ['mcp_bridge'],
    policyBoundary: 'workspace',
    localOnly: false,
    sharedAllowed: true,
    hostedAllowed: false,
    externalActionsAllowed: true,
    auditMode: 'full',
    riskLevel: 'write_safe',
    approvalLevel: 'CONFIRM',
    inputContract: {
      summary: 'Connected-app intent plus selected MCP server, surface, and policy boundary.',
    },
    outputContract: {
      summary: 'MCP prompt/resource/tool result with redacted audit trace and selected surface.',
    },
    verificationMode: 'trace',
    outputShape: 'artifact',
    selectionWeight: 24,
    stageTemplates: [
      {
        id: 'mcp-discovery',
        title: 'Discovery',
        summary: 'Resolve the live MCP surface before invoking anything.',
        kind: 'mcp',
        capabilityId: 'mcp_bridge',
      },
      {
        id: 'mcp-routing',
        title: 'Route',
        summary: 'Choose the smallest prompt, resource, or tool that fits the task.',
        kind: 'capability',
      },
      {
        id: 'mcp-evaluate',
        title: 'Evaluate',
        summary: 'Keep the trace auditable and make the chosen action obvious.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'optimization_decision',
    title: 'Optimization Decision',
    version: '1.0.0',
    description: 'Models assignment, routing, scheduling, and resource allocation problems with classical and quantum-inspired solver comparison.',
    domain: 'optimization',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [
        'optimization',
        'optimisation',
        'assignment',
        'task allocation',
        'görev dağıtımı',
        'routing',
        'route optimization',
        'rota optimizasyonu',
        'scheduling',
        'resource allocation',
        'resource distribution',
        'resource_allocation',
        'kaynak tahsisi',
        'kaynakları dağıt',
        'minimum cost',
        'en düşük maliyet',
        'best allocation',
        'best distribution',
        'en iyi dağıtım',
        'load balancing',
        'QUBO',
        'Ising',
        'quantum-inspired',
        'kuantum-esinli',
        'hybrid solution',
      ],
      intents: ['procedural', 'comparison'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: ['optimization_solve', 'tool_bridge', 'math_exact', 'math_decimal', 'chart_generate'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: false,
    auditMode: 'summary',
    riskLevel: 'read_only',
    approvalLevel: 'AUTO',
    inputContract: {
      summary: 'Optimization intent or typed problem model with objective, variables, constraints, and demo selector.',
    },
    outputContract: {
      summary: 'JSON and Markdown decision report with model, QUBO, solver comparison, and selected solution.',
    },
    verificationMode: 'summary',
    outputShape: 'report',
    selectionWeight: 33,
    stageTemplates: [
      {
        id: 'optimization-model',
        title: 'Model problem',
        summary: 'Classify the problem type, extract variables, constraints, and objective.',
        kind: 'analysis',
        capabilityId: 'optimization_solve',
      },
      {
        id: 'optimization-qubo',
        title: 'Build QUBO',
        summary: 'Create the binary QUBO/Ising-compatible representation without claiming quantum hardware.',
        kind: 'capability',
        capabilityId: 'optimization_solve',
      },
      {
        id: 'optimization-solvers',
        title: 'Compare solvers',
        summary: 'Run greedy, simulated annealing, and small QUBO brute-force fallback where possible.',
        kind: 'capability',
        capabilityId: 'optimization_solve',
      },
      {
        id: 'optimization-report',
        title: 'Decision report',
        summary: 'Explain cost, feasibility, violations, selected solution, and technical summary.',
        kind: 'synthesis',
      },
    ],
    techniques: [
      agenticTechniques.optimizationModelingPlaybook,
      agenticTechniques.optimizationSolverComparator,
      agenticTechniques.optimizationDecisionReporter,
    ],
  }),
  skillManifestSchema.parse({
    id: 'deterministic_math',
    title: 'Deterministic Math',
    version: '1.0.0',
    description: 'Uses bounded arithmetic and structured transforms for numeric tasks.',
    domain: 'calculation',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: ['calculate', 'math', 'sum', 'subtract', 'multiply', 'divide', 'percentage', 'ratio', 'decimal', 'precision'],
      intents: ['direct_answer', 'procedural'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: ['tool_bridge', 'math_exact', 'math_decimal', 'chart_generate'],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: false,
    hostedAllowed: false,
    externalActionsAllowed: false,
    auditMode: 'summary',
    riskLevel: 'read_only',
    approvalLevel: 'AUTO',
    inputContract: {
      summary: 'Numeric expression or structured deterministic transform request.',
    },
    outputContract: {
      summary: 'Deterministic numeric answer with stable precision.',
    },
    verificationMode: 'summary',
    outputShape: 'answer',
    selectionWeight: 22,
    stageTemplates: [
      {
        id: 'math-analysis',
        title: 'Analysis',
        summary: 'Parse the expression and choose the deterministic arithmetic path.',
        kind: 'analysis',
        capabilityId: 'math_exact',
      },
      {
        id: 'math-execution',
        title: 'Execution',
        summary: 'Run the local calculation with bounded precision.',
        kind: 'capability',
        capabilityId: 'tool_bridge',
      },
      {
        id: 'math-evaluate',
        title: 'Evaluate',
        summary: 'Confirm the result is deterministic and stable.',
        kind: 'evaluation',
      },
    ],
  }),
  skillManifestSchema.parse({
    id: 'general_answer',
    title: 'General Answer',
    version: '1.0.0',
    description: 'Fallback skill when no specialized runtime path is a stronger match.',
    domain: 'general',
    enabled: true,
    source: {
      kind: 'builtin',
    },
    triggers: {
      keywords: [],
      intents: ['direct_answer'],
      urlSensitive: false,
      documentSensitive: false,
      mcpSensitive: false,
      actionSensitive: false,
    },
    preferredCapabilityIds: [],
    policyBoundary: 'local',
    localOnly: true,
    sharedAllowed: true,
    hostedAllowed: true,
    externalActionsAllowed: false,
    auditMode: 'summary',
    riskLevel: 'read_only',
    approvalLevel: 'AUTO',
    inputContract: {
      summary: 'General natural-language request without a stronger specialized runtime path.',
    },
    outputContract: {
      summary: 'Concise direct answer.',
    },
    verificationMode: 'summary',
    outputShape: 'answer',
    selectionWeight: 1,
    stageTemplates: [
      {
        id: 'general-analysis',
        title: 'Analysis',
        summary: 'Resolve the request directly with the fewest moving parts.',
        kind: 'analysis',
      },
      {
        id: 'general-synthesis',
        title: 'Synthesis',
        summary: 'Answer clearly without introducing unnecessary surface area.',
        kind: 'synthesis',
      },
      {
        id: 'general-evaluate',
        title: 'Evaluate',
        summary: 'Keep the response concise and easy to trust.',
        kind: 'evaluation',
      },
    ],
    techniques: [
      agenticTechniques.hookGenerator,
      agenticTechniques.structuredCopywritingSkill,
      agenticTechniques.toneStyleEnforcer,
      agenticTechniques.videoScriptGenerator,
      agenticTechniques.videoEditingPlanner,
    ],
  }),
];

export function buildBuiltinSkillCatalog(): SkillManifest[] {
  return builtinSkillDefinitions.map((skill) => skillManifestSchema.parse(skill));
}
