export const metadata = {
  title: 'Wiqo Next Scaffold',
  description: 'Professional starter generated by Wiqo',
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>{children}</body>
    </html>
  )
}
